version: '3'

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: meraki_wordpress
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=merakiweddingplanner
      - WORDPRESS_DB_USER=merakiwp
      - WORDPRESS_DB_PASSWORD=Scrap-layup-7dipped
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - meraki_network
    command: >
      bash -c "cp -rn /usr/src/wordpress/* /var/www/html/ 
      && chown -R www-data:www-data /var/www/html 
      && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: meraki_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - wordpress
    networks:
      - meraki_network

  mysql:
    image: mysql:8.0
    container_name: meraki_mysql
    restart: always
    environment:
      MYSQL_DATABASE: merakiweddingplanner
      MYSQL_USER: merakiwp
      MYSQL_PASSWORD: Scrap-layup-7dipped
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./merakiweddingplanner-com.sql:/docker-entrypoint-initdb.d/merakiweddingplanner-com.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "merakiwp", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meraki_network

volumes:
  mysql_data:
  wordpress_data:

networks:
  meraki_network:
    driver: bridge 